/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphdemo;

import java.awt.BorderLayout;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Admin
 */
public class GraphJFrame extends javax.swing.JFrame {

    private final graph graph = new graph();
    JFileChooser filechooser = new JFileChooser();

    /**
     * Creates new form GraphJFrame
     */
    public GraphJFrame() {
        initComponents();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        paper.setLayout(new BorderLayout());
        paper.add(graph, BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtResult = new javax.swing.JTextField();
        paper = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        muOpen = new javax.swing.JMenuItem();
        mySavetoList = new javax.swing.JMenuItem();
        mySvaeToMatrix = new javax.swing.JMenuItem();
        myClear = new javax.swing.JMenuItem();
        myExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MyDFS = new javax.swing.JMenuItem();
        myBFS = new javax.swing.JMenuItem();
        myFindPath = new javax.swing.JMenuItem();
        myPrim = new javax.swing.JMenuItem();
        myKruskal = new javax.swing.JMenuItem();
        myIVC = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        myHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtResult, javax.swing.GroupLayout.DEFAULT_SIZE, 1251, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtResult, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout paperLayout = new javax.swing.GroupLayout(paper);
        paper.setLayout(paperLayout);
        paperLayout.setHorizontalGroup(
            paperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        paperLayout.setVerticalGroup(
            paperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        muOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        muOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/open.png"))); // NOI18N
        muOpen.setText("Open");
        muOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muOpenActionPerformed(evt);
            }
        });
        jMenu1.add(muOpen);

        mySavetoList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mySavetoList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images-20230308T070045Z-001/images/list.png"))); // NOI18N
        mySavetoList.setText("Save to List");
        mySavetoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mySavetoListActionPerformed(evt);
            }
        });
        jMenu1.add(mySavetoList);

        mySvaeToMatrix.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mySvaeToMatrix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images-20230308T070045Z-001/images/matrix.png"))); // NOI18N
        mySvaeToMatrix.setText("Save to Matrix");
        mySvaeToMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mySvaeToMatrixActionPerformed(evt);
            }
        });
        jMenu1.add(mySvaeToMatrix);

        myClear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        myClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/clear.png"))); // NOI18N
        myClear.setText("Clear");
        myClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myClearActionPerformed(evt);
            }
        });
        jMenu1.add(myClear);

        myExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        myExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/exit.png"))); // NOI18N
        myExit.setText("Exit");
        myExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myExitActionPerformed(evt);
            }
        });
        jMenu1.add(myExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Algorithm");

        MyDFS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        MyDFS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/tree.png"))); // NOI18N
        MyDFS.setText("DFS");
        MyDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyDFSActionPerformed(evt);
            }
        });
        jMenu2.add(MyDFS);

        myBFS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        myBFS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/tree.png"))); // NOI18N
        myBFS.setText("BFS");
        myBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myBFSActionPerformed(evt);
            }
        });
        jMenu2.add(myBFS);

        myFindPath.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        myFindPath.setText("Find Shortest Path");
        myFindPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myFindPathActionPerformed(evt);
            }
        });
        jMenu2.add(myFindPath);

        myPrim.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        myPrim.setText("Find Minimun Spanning Tree (Prim)");
        myPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myPrimActionPerformed(evt);
            }
        });
        jMenu2.add(myPrim);

        myKruskal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        myKruskal.setText("Find Minimun Spanning Tree (Krusakal )");
        myKruskal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myKruskalActionPerformed(evt);
            }
        });
        jMenu2.add(myKruskal);

        myIVC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        myIVC.setText("Isolated vertices counting");
        myIVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myIVCActionPerformed(evt);
            }
        });
        jMenu2.add(myIVC);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        myHelp.setText("Help Contents");
        myHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myHelpActionPerformed(evt);
            }
        });
        jMenu3.add(myHelp);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myFindPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myFindPathActionPerformed
        // TODO add your handling code here:
        txtResult.setText(graph.printDijkstra());
    }//GEN-LAST:event_myFindPathActionPerformed

    private void MyDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyDFSActionPerformed
        // TODO add your handling code here:
        txtResult.setText(graph.printDFS());
    }//GEN-LAST:event_MyDFSActionPerformed

    private void myBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myBFSActionPerformed
        // TODO add your handling code here:
        txtResult.setText(graph.printBFS());

    }//GEN-LAST:event_myBFSActionPerformed

    private void myPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myPrimActionPerformed
        // TODO add your handling code here:
        txtResult.setText(graph.printMSTPrim());
    }//GEN-LAST:event_myPrimActionPerformed

    private void myKruskalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myKruskalActionPerformed
        // TODO add your handling code here:
          txtResult.setText(graph.printDijkstra());
    }//GEN-LAST:event_myKruskalActionPerformed

    private void myIVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myIVCActionPerformed
        // TODO add your handling code here:
           txtResult.setText(graph.printIVC());
    }//GEN-LAST:event_myIVCActionPerformed

    private void muOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muOpenActionPerformed
        // TODO add your handling code here:
        filechooser.setFileFilter(new FileNameExtensionFilter("Graph(* list * matrix)", "list", "matrix"));
        if (filechooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File openFile = filechooser.getSelectedFile();
            if (openFile.getName().endsWith(".list")) {
                graph.createGraphList(openFile);
            } else if (openFile.getName().endsWith(".matrix")) {
                graph.createGraphMatrix(openFile);
            }
        }
    }//GEN-LAST:event_muOpenActionPerformed
    public File getSaveFile(FileNameExtensionFilter filter, String fileName) {
        filechooser.setFileFilter(filter);
        filechooser.setSelectedFile(new File(fileName));
        if (filechooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            return filechooser.getSelectedFile();
        }
        return null;
    }

    private void mySavetoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mySavetoListActionPerformed
        // TODO add your handling code here:
        File saveFile = getSaveFile(new FileNameExtensionFilter("Graph data", "list"), "Graph.list");
        graph.saveToList(saveFile);
    }//GEN-LAST:event_mySavetoListActionPerformed

    private void mySvaeToMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mySvaeToMatrixActionPerformed
        // TODO add your handling code here:
        File saveFile = getSaveFile(new FileNameExtensionFilter("Graph data", "matrix"), "Graph.matrix");
        graph.saveToMatrix(saveFile);
    }//GEN-LAST:event_mySvaeToMatrixActionPerformed

    private void myClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myClearActionPerformed
        // TODO add your handling code here:
        graph.clear();
    }//GEN-LAST:event_myClearActionPerformed

    private void myExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_myExitActionPerformed

    private void txtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultActionPerformed

    private void myHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myHelpActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog(this, "<html> ##### Draws vertices #####<br/> #1. Hold <b><font color=\\\"red\\\">ctrl</font></b> and click on space<br/> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to add new vertex.<br/> #2. Hold <b><font color=\\\"red\\\">Shift</font></b> and click on the vertex that you <br/> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;want to remove.<br/> #3. Drag and drop a vertex to move it.<br/><br/> ##### Draws edges #####<br/> #1. Select start vertex <br/> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(click it again to unselect).<br/> #2. Select destination vertex.<br/> #3. Input edge's value.<br/> #4. Click on value of the exist edge to update. </html>");
    }//GEN-LAST:event_myHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GraphJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MyDFS;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem muOpen;
    private javax.swing.JMenuItem myBFS;
    private javax.swing.JMenuItem myClear;
    private javax.swing.JMenuItem myExit;
    private javax.swing.JMenuItem myFindPath;
    private javax.swing.JMenuItem myHelp;
    private javax.swing.JMenuItem myIVC;
    private javax.swing.JMenuItem myKruskal;
    private javax.swing.JMenuItem myPrim;
    private javax.swing.JMenuItem mySavetoList;
    private javax.swing.JMenuItem mySvaeToMatrix;
    private javax.swing.JPanel paper;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
